package generator

import (
	"fmt"
	"io"
	"log"
	"path/filepath"
	"regexp"
	"strings"

	b "github.com/malpa222/postlite/lib/blogfsys"
	"github.com/malpa222/postlite/lib/parser"
)

// Basic site tree:
// mysite/
// ├── assets/       # all media (images etc.)
// ├── index.md      # landing page
// ├── posts/
// ├── public/       # auto generated by postlite
// └── styles

type Generator interface {
	GenerateStaticContent() error
}

type generator struct {
	fsys b.BlogFsys
}

func NewGenerator(root string) (Generator, error) {
	fsys, err := b.NewBlogFsys(root)
	if err != nil {
		return nil, err
	}

	// set up filesystem
	if err := fsys.Clean(b.Public); err != nil {
		return nil, err
	}

	gen := generator{fsys: fsys}

	return &gen, nil
}

func (g *generator) GenerateStaticContent() error {
	// find root directories
	if dirs, err := g.fsys.Find(1, dirFilter); err != nil {
		return err
	} else {
		g.copyAssets(dirs)
	}

	// find all markdown documents
	if files, err := g.fsys.Find(0, mdFilter); err != nil {
		return err
	} else {
		g.parseMarkdown(files)
	}

	return nil
}

func (g *generator) copyAssets(dirs []b.DataSource) {
	for _, dir := range dirs {
		log.Printf("Copying %s ...", dir.GetPath())

		dst := filepath.Join(b.Public, dir.GetPath())
		if err := g.fsys.Copy(dir, dst); err != nil {
			log.Printf("Copying failed: %s", err)
		}
	}
}

func (g *generator) parseMarkdown(files []b.DataSource) {
	for _, file := range files {
		log.Printf("Parsing %s ...", file.GetPath())

		src, err := file.Open()
		if err != nil {
			log.Printf("Couldn't open %s: %s", file.GetPath(), err)
			continue
		}
		defer src.Close()

		md, err := io.ReadAll(src)
		if err != nil {
			log.Printf("Couldn't read %s: %s", file.GetPath(), err)
			continue
		}

		html := parser.ParseMarkdown(md)

		dst := strings.Replace(file.GetPath(), ".md", ".html", 1)
		dst = filepath.Join(b.Public, dst)

		var outFile = b.BlogMemBuf{Buf: html}

		if err := g.fsys.Copy(&outFile, dst); err != nil {
			log.Printf("Copying %s failed: %s", file.GetPath(), err)
			continue
		}
	}
}

var mdFilter b.FilterFunc = func(file b.DataSource) bool {
	return file.GetKind() == b.MD
}

var dirFilter b.FilterFunc = func(file b.DataSource) bool {
	if file.GetKind() != b.Dir {
		return false
	}

	pattern := fmt.Sprintf("%s|%s", b.Public, b.Posts)
	re := regexp.MustCompile(pattern)

	return !re.MatchString(file.GetPath())
}
