name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24' 

    - name: Test
      run: |
        go clean -testcache
        go test ./...

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24' 

    - name: Build
      run: |
        go mod tidy
        go build -o postlite -ldflags "-s -w"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: postlite
        path: postlite

  build-package:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24' 

    - name: Build
      run: |
        go install github.com/malpa222/postlite@latest
        postlite
